Update README.md
stat6250-w18/course-questions-wiki pull request #130
Opened 2018-01-17 05:51 UTC by sbagdi-stat6250

2018-01-17 16:39 UTC, prof-lankham requested changes
Please resolve feedback and DM me in Slack with the PR URL for re-evaluation

2018-01-17 16:39 UTC, prof-lankham commented on week-03/README.md
> +- *Question* (sbagdi-stat6250): Which operator is used to select observations that include a specified string?
Invalid question for a Weekly Quiz; you're not creating a quiz for someone else. The instructions specify that you should be asking questions about SAS programming that **you** actually have, as prompted by concepts in textbook problems and recipes.

2018-01-17 16:39 UTC, prof-lankham commented on week-03/README.md
> +- *Question* (sbagdi-stat6250): What does the DESCENDING option does? And to which statement should it be added?
Invalid question for a Weekly Quiz; you're not creating a quiz for someone else. The instructions specify that you should be asking questions about SAS programming that **you** actually have, as prompted by concepts in textbook problems and recipes.

2018-01-17 16:39 UTC, prof-lankham commented on week-03/README.md
> +- *Question* (sbagdi-stat6250): Which of the following is true for SAS statements?
Invalid question for a Weekly Quiz; you're not creating a quiz for someone else. The instructions specify that you should be asking questions about SAS programming that **you** actually have, as prompted by concepts in textbook problems and recipes.

2018-01-24 06:18 UTC, SurbhiBagdi reviewed
Professor. In the files changes tab, I see the updated file. I hope it's what I had to do.

2018-01-30 03:46 UTC, merged