Week 4 Quiz submission from asharda-stat6250
stat6250-w18/course-questions-wiki pull request #359
Opened 2018-03-11 06:00 UTC by asharda-stat6250

Week 4 Quiz submission from asharda-stat6250

2018-03-12 15:15 UTC, prof-lankham requested changes
Please update PR and DM me in Slack with PR URL for re-evaluation

2018-03-12 15:15 UTC, prof-lankham commented on week-04/README.md
> +- *Answer* (asharda-stat6250):
Please update code sample with code fence; see https://help.github.com/articles/creating-and-highlighting-code-blocks/

2018-03-12 15:15 UTC, prof-lankham commented on week-04/README.md
> + - *Answer* (asharda-stat6250):PROC FORMAT
This answer should be expanded

2018-03-12 15:15 UTC, prof-lankham commented on week-04/README.md
> +- 282 - (remember that you can use the NOPRINT option to suppress the default report). By contrast, to produce a report in PROC SUMMARY, you must include a PRINT option in the PROC SUMMARY statement.
Please remove line break from this answer

2018-03-13 16:24 UTC, prof-lankham requested changes
Before this PR can be merged, please remove line breaks from answers and DM me in Slack with PR URL.

2018-03-13 16:24 UTC, prof-lankham commented on week-04/README.md
> +wit a semicolon. The first statement calls PROC FORMAT. The second statement is a value clause that defines the name and contents of the user-defined format. The final statement is the run statement
Remove line break here.

2018-03-13 16:24 UTC, prof-lankham commented on week-04/README.md
> +- 282 - (remember that you can use the NOPRINT option to suppress the default report). By contrast, to produce a report in PROC SUMMARY, you must include a PRINT option in the PROC SUMMARY statement.
Remove line break here.

2018-03-16 22:26 UTC, asharda-stat6250 commented
Deleted branch as was unable to fork,closing it.submitted a new PR

2018-03-16 22:26 UTC, closed without merging