Week 5 Quiz submission from asharda-stat6250
stat6250-w18/course-questions-wiki pull request #361
Opened 2018-03-12 19:25 UTC by asharda-stat6250

Week 5 Quiz submission from asharda-stat6250

2018-03-13 01:03 UTC, prof-lankham requested changes
Please update PR and DM me in Slack with PR URL when ready for re-evaluation

2018-03-13 01:03 UTC, prof-lankham commented on week-05/README.md
> +- *Answer* (asharda-stat6250):
No bullet points or line breaks should be used in answers

2018-03-13 01:03 UTC, prof-lankham commented on week-05/README.md
> +or end your SAS session.
No bullet points or line breaks should be used in answers

2018-03-16 23:39 UTC, asharda-stat6250 commented
Did submit a new PR

2018-03-16 23:39 UTC, closed without merging